### ISSUE TITLE
Slow progress and very far behind

### ISSUE THREAD

**Issue by ChiefJDUB** [soneek/Pokemon-Black2-White2-Story-Translation-Files-2012#14]
i like the fact that you have the original start screen but you guys are very far behind and looks like you have given up also

**Comment by Chase-san** [comment]
We we're not that far behind, you know very little about percent completion.

**Comment by ChiefJDUB** [comment]
i was talking about from the day i posted i looked at both pages and its pretty far behind and like i said looks like you have given up. the best one is English Translation Progress (current patch is v2.1):
Items: 100%
Pokémon: 100%
Abilities: 100%
Trainers: 100%
Moves: 100%
Text: 35%
Graphics: 88%

**Comment by Chase-san** [comment]
You're quoting estimations, really?
